# Generated by Django 3.0.2 on 2020-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_modelalgorithm_modelmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelalgorithm',
            name='youtube',
            field=models.CharField(max_length=150),
        ),
    ]
